[workspace]
members = ["src/*"]
version = "3.6.1"
license = "MIT"

[workspace.dependencies]
ChalkLua = "github.com/roblox/chalk-lua@0.2.0"
LuauPolyfill = "github.com/roblox/luau-polyfill@1"
RegExp = "github.com/roblox/luau-regexp@0.2.1"
Promise = "github.com/roblox/roblox-lua-promise@3.3.0"
React = "github.com/roblox/roact-alignment.git@17.0.1"
ReactIs = "github.com/roblox/roact-alignment.git@17.0.1"
ReactTestRenderer = "github.com/roblox/roact-alignment.git@17.0.1"
Picomatch = "github.com/Roblox/picomatch-lua@0.4.0"
