[package]
name = "JestBenchmark"
authors = { workspace = true }
description = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }
version = { workspace = true }
license = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[config]
registry_index = "true"

[dependencies]
JestGlobals = { path = "../jest-globals" }
LuauPolyfill = { workspace = true }
JestTypes = { path = "../jest-types" }
