[package]
name = "JestConfig"
version = { workspace = true }
license = { workspace = true }
authors = [
	"Chris Trze≈õniewski <k.trzesniewski@gmail.com>",
]
content_root = "src"
files = ["*", "!**/__tests__/**", "!**/__mocks__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
Promise = { workspace = true }
ChalkLua = { workspace = true }
RegExp = { workspace = true }
JestTypes = { path = "../jest-types" }
JestGetType = { path = "../jest-get-type" }
JestUtil = { path = "../jest-util" }
JestEnvironmentLuau = { path = "../jest-environment-luau" }
JestValidate = { path = "../jest-validate" }
JestRobloxShared = { path = "../jest-roblox-shared" }

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
JestSnapshotSerializerRaw = { path = "../jest-snapshot-serializer-raw" }
PrettyFormat = { path = "../pretty-format" }
