[package]
name = "JestConsole"
version = { workspace = true }
license = { workspace = true }
author = { workspace = true }
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
JestTypes = { path = "../jest-types" }
ChalkLua = { workspace = true }
JestUtil = { path = "../jest-util" }
JestMessageUtil = { path = "../jest-message-util" }
JestMock = { path = "../jest-mock" }
JestEach = { path = "../jest-each" }
RobloxShared = { path = "../roblox-shared" }

[dev_dependencies]
Jest = { path = "../jest" }
Expect = { path = "../expect" }
