[package]
name = "JestMessageUtil"
version = { workspace = true }
license = { workspace = true }
author = "Roblox"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dependencies]
LuauPolyfill = { workspace = true }
ChalkLua = { workspace = true }
RegExp = { workspace = true }
JestTypes = { path = "../jest-types"}
PrettyFormat = { path = "../pretty-format"}
RobloxShared = { path = "../roblox-shared"}

[dev_dependencies]
JestGlobals = { path = "../jest-globals" }
JestSnapshotSerializerRaw = { path = "../jest-snapshot-serializer-raw" }
Promise = { workspace = true }
